### ISSUE TITLE
Is the Java implementation of the Kneedle algorithm available in this repo?

### ISSUE THREAD

**Issue by jagandecapri** [kneedetection/kneedle-java#1]
Hi @fkleedorfer,

I am unable to obtain the Java implementation of the Kneedle algorithm from this repo. Is it available?

**Comment by fkleedorfer** [comment]
Hi,
I started out with this as an independent implementation but we ended up doing it as a part of the webofneeda project. The code is there, but not as generic as I wanted it here.

**Comment by fkleedorfer** [comment]
Here's the test: https://github.com/researchstudio-sat/webofneeds/blob/bb732eb9080551838a1f72636e8042cc0bf67f55/webofneeds/won-matcher-solr/src/test/java/won/matcher/solr/utils/KneedleTest.java

**Comment by fkleedorfer** [comment]
If you want to contribute, it would be great if you carved that out of webofneeds, put it in your kneedle-java fork, and made a PR!

**Comment by jagandecapri** [comment]
Hei @fkleedorfer,

Sorry for the late reply. Yeap, got it. I'll make a PR if I'm able to. Thanks a lot for your help! :)
